[versions]
appcompat = "1.7.1"
constraintlayout = "2.2.1"
espresso-core = "3.7.0"
gradle = "9.3.0"
gradle-toolchains-foojay-resolver-convention = "1.0.0"
junit = "4.13.2"
preference = "1.2.1"
runner = "1.7.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
foojay = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "gradle-toolchains-foojay-resolver-convention" }
